### ISSUE TITLE
Typo : SUWIKI-AMDIN

### ISSUE THREAD

**Issue by FeelingXD** [uswLectureEvaluation/admin#1]
![image](https://github.com/uswLectureEvaluation/SUWIKI-AMDIN/assets/45274316/b91e839f-cd33-4485-adee-c929a698d12e)

레포명이 오타인것 같습니다
SUWIKI-AMDIN -> SUWIKI-ADMIN(?).

**Comment by tooooo1** [comment]
제보 감사합니다 :)

**Comment by tooooo1** [comment]
<img width="286" alt="스크린샷 2024-03-18 오후 3 16 56" src="https://github.com/uswLectureEvaluation/admin/assets/77133565/328affee-09a3-4026-b451-81776809f3ec">

@FeelingXD 해결했어요 

cc. @eun-hak
